- name: Télécharger l’agent Zabbix Windows
  ansible.windows.win_get_url:
    url: https://cdn.zabbix.com/zabbix/binaries/stable/7.4/7.4.9/zabbix_agent-7.4.9-windows-amd64-openssl.msi
    dest: C:\Temp\zabbix_agent.msi

- name: Installer l’agent Zabbix
  ansible.windows.win_package:
    path: C:\Temp\zabbix_agent.msi
    state: present

- name: Configurer le service Zabbix Agent
  ansible.windows.win_template:
    src: zabbix_agentd.conf.j2
    dest: C:\Program Files\Zabbix Agent\zabbix_agentd.conf

- name: Redémarrer le service Zabbix Agent
  ansible.windows.win_service:
    name: Zabbix Agent
    start_mode: auto
    state: restarted
