# roles/postgres_zabbix/tasks/configure_pg_hba.yml

- name: Ajouter accès Zabbix à pg_hba.conf
  ansible.builtin.lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    line: "host    {{ zabbix_db_name }}    {{ zabbix_db_user }}    {{ item }}/32    md5"
    create: yes
    insertafter: EOF
    state: present
  loop: "{{ zabbix_allowed_hosts }}"
  notify: Restart PostgreSQL
