- name: Activer le service w32time (NTP) sur Windows
  ansible.windows.win_service:
    name: w32time
    start_mode: auto
    state: started

- name: Configurer les serveurs NTP sur Windows
  ansible.windows.win_regedit:
    path: HKLM\SYSTEM\CurrentControlSet\Services\W32Time\Parameters
    name: NtpServer
    data: "{{ ntp_servers | join(',') }}"
    type: string

- name: Forcer la resynchro NTP sur Windows
  ansible.windows.win_command: w32tm /resync
